"""empty message

Revision ID: 1c62fbbc087e
Revises: 8ec875a2736e
Create Date: 2025-05-07 23:36:42.117820

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1c62fbbc087e'
down_revision = '8ec875a2736e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('submission', schema=None) as batch_op:
        batch_op.add_column(sa.Column('start_time', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('end_time', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('attempts', sa.Integer(), nullable=True))
        batch_op.alter_column('code',
               existing_type=sa.TEXT(),
               nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('submission', schema=None) as batch_op:
        batch_op.alter_column('code',
               existing_type=sa.TEXT(),
               nullable=False)
        batch_op.drop_column('attempts')
        batch_op.drop_column('end_time')
        batch_op.drop_column('start_time')

    # ### end Alembic commands ###
