"""empty message

Revision ID: 290dbfe93a5b
Revises: 
Create Date: 2025-05-09 13:46:54.746720

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '290dbfe93a5b'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('question', schema=None) as batch_op:
        batch_op.alter_column('test_cases',
               existing_type=sa.VARCHAR(length=255),
               nullable=True)

    with op.batch_alter_table('submission', schema=None) as batch_op:
        batch_op.add_column(sa.Column('total_attemps', sa.Integer(), nullable=True))
        batch_op.drop_column('tests_run')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('submission', schema=None) as batch_op:
        batch_op.add_column(sa.Column('tests_run', sa.INTEGER(), nullable=True))
        batch_op.drop_column('total_attemps')

    with op.batch_alter_table('question', schema=None) as batch_op:
        batch_op.alter_column('test_cases',
               existing_type=sa.VARCHAR(length=255),
               nullable=False)

    # ### end Alembic commands ###
