"""empty message

Revision ID: 2e5216961555
Revises: 290dbfe93a5b
Create Date: 2025-05-09 13:51:19.653826

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2e5216961555'
down_revision = '290dbfe93a5b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('submission', schema=None) as batch_op:
        batch_op.add_column(sa.Column('total_attempts', sa.Integer(), nullable=True))
        batch_op.drop_column('total_attemps')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('submission', schema=None) as batch_op:
        batch_op.add_column(sa.Column('total_attemps', sa.INTEGER(), nullable=True))
        batch_op.drop_column('total_attempts')

    # ### end Alembic commands ###
