"""empty message

Revision ID: 6f55afa7a3f3
Revises: eb34d013ade8
Create Date: 2025-05-07 22:21:16.654965

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6f55afa7a3f3'
down_revision = 'eb34d013ade8'
branch_labels = None
depends_on = None


def upgrade():
    from sqlalchemy import Table, MetaData

    meta = MetaData(bind=op.get_bind())
    my_table = Table('Question', meta)

    my_table_constraints = list(my_table.constraints)
    my_constraint_names = list(map(lambda x: x.name, my_table_constraints))
    print(my_constraint_names, flush=True)
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('profile_share')
    with op.batch_alter_table('question', schema=None) as batch_op:
        batch_op.add_column(sa.Column('author_id', sa.Integer(), nullable=False))
        batch_op.alter_column('short_desc',
               existing_type=sa.VARCHAR(length=512),
               nullable=False)
        batch_op.alter_column('full_desc',
               existing_type=sa.TEXT(),
               nullable=False)
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(None, 'user', ['author_id'], ['id'], ondelete='CASCADE')
        batch_op.drop_column('author_username')

    with op.batch_alter_table('rating', schema=None) as batch_op:
        batch_op.alter_column('user_id',
               existing_type=sa.VARCHAR(length=64),
               type_=sa.Integer(),
               existing_nullable=False)
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(None, 'user', ['user_id'], ['id'], ondelete='CASCADE')

    with op.batch_alter_table('submission', schema=None) as batch_op:
        batch_op.add_column(sa.Column('start_time', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('end_time', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('attempts', sa.Integer(), nullable=True))
        batch_op.alter_column('user_id',
               existing_type=sa.VARCHAR(length=64),
               type_=sa.Integer(),
               existing_nullable=False)
        batch_op.alter_column('code',
               existing_type=sa.TEXT(),
               nullable=True)
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(None, 'user', ['user_id'], ['id'], ondelete='CASCADE')

    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('id', sa.Integer(), nullable=False))
        batch_op.add_column(sa.Column('attempted_questions', sa.Integer(), nullable=True))
        batch_op.create_unique_constraint(None, ['username'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='unique')
        batch_op.drop_column('attempted_questions')
        batch_op.drop_column('id')

    with op.batch_alter_table('submission', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(None, 'user', ['user_id'], ['username'], ondelete='CASCADE')
        batch_op.alter_column('code',
               existing_type=sa.TEXT(),
               nullable=False)
        batch_op.alter_column('user_id',
               existing_type=sa.Integer(),
               type_=sa.VARCHAR(length=64),
               existing_nullable=False)
        batch_op.drop_column('attempts')
        batch_op.drop_column('end_time')
        batch_op.drop_column('start_time')

    with op.batch_alter_table('rating', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(None, 'user', ['user_id'], ['username'], ondelete='CASCADE')
        batch_op.alter_column('user_id',
               existing_type=sa.Integer(),
               type_=sa.VARCHAR(length=64),
               existing_nullable=False)

    with op.batch_alter_table('question', schema=None) as batch_op:
        batch_op.add_column(sa.Column('author_username', sa.VARCHAR(length=64), nullable=False))
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(None, 'user', ['author_username'], ['username'], ondelete='CASCADE')
        batch_op.alter_column('full_desc',
               existing_type=sa.TEXT(),
               nullable=True)
        batch_op.alter_column('short_desc',
               existing_type=sa.VARCHAR(length=512),
               nullable=True)
        batch_op.drop_column('author_id')

    op.create_table('profile_share',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('owner_id', sa.INTEGER(), nullable=False),
    sa.Column('shared_with_id', sa.INTEGER(), nullable=False),
    sa.ForeignKeyConstraint(['owner_id'], ['user.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['shared_with_id'], ['user.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###
