"""empty message

Revision ID: 6fbf533c8bdc
Revises: 7e545bce7c85
Create Date: 2025-05-12 17:19:53.045423

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6fbf533c8bdc'
down_revision = '7e545bce7c85'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('question', schema=None) as batch_op:
        batch_op.add_column(sa.Column('avg_attempts', sa.Float(), nullable=True))
        batch_op.drop_column('avg_tests')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('question', schema=None) as batch_op:
        batch_op.add_column(sa.Column('avg_tests', sa.FLOAT(), nullable=True))
        batch_op.drop_column('avg_attempts')

    # ### end Alembic commands ###
