"""empty message

Revision ID: 7e545bce7c85
Revises: 1c62fbbc087e
Create Date: 2025-05-07 23:37:48.250881

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7e545bce7c85'
down_revision = '1c62fbbc087e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('attempted_questions', sa.Integer(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('attempted_questions')

    # ### end Alembic commands ###
