"""empty message

Revision ID: 8ec875a2736e
Revises: 5e52f5f7c7a9
Create Date: 2025-05-07 23:20:19.557363

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8ec875a2736e'
down_revision = '5e52f5f7c7a9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('profile_share',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('owner_id', sa.Integer(), nullable=False),
    sa.Column('shared_with_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['owner_id'], ['user.id'], name='fk_ProfileShare_User_1', ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['shared_with_id'], ['user.id'], name='fk_ProfileShare_User_2', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('profile_share')
    # ### end Alembic commands ###
