"""Added id as primary key on Rating db

Revision ID: a77579d8b794
Revises: 7e545bce7c85
Create Date: 2025-05-09 19:12:14.722573

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a77579d8b794'
down_revision = '7e545bce7c85'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('rating', schema=None) as batch_op:
        batch_op.add_column(sa.Column('id', sa.Integer(), nullable=False))
        batch_op.alter_column('question_id',
               existing_type=sa.INTEGER(),
               nullable=True)

    with op.batch_alter_table('submission', schema=None) as batch_op:
        batch_op.add_column(sa.Column('total_attempts', sa.Integer(), nullable=True))
        batch_op.alter_column('code',
               existing_type=sa.TEXT(),
               nullable=False)
        batch_op.drop_column('attempts')
        batch_op.drop_column('tests_run')
        batch_op.drop_column('start_time')
        batch_op.drop_column('end_time')

    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('attempted_questions')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('attempted_questions', sa.INTEGER(), nullable=True))

    with op.batch_alter_table('submission', schema=None) as batch_op:
        batch_op.add_column(sa.Column('end_time', sa.FLOAT(), nullable=True))
        batch_op.add_column(sa.Column('start_time', sa.FLOAT(), nullable=True))
        batch_op.add_column(sa.Column('tests_run', sa.INTEGER(), nullable=True))
        batch_op.add_column(sa.Column('attempts', sa.INTEGER(), nullable=True))
        batch_op.alter_column('code',
               existing_type=sa.TEXT(),
               nullable=True)
        batch_op.drop_column('total_attempts')

    with op.batch_alter_table('rating', schema=None) as batch_op:
        batch_op.alter_column('question_id',
               existing_type=sa.INTEGER(),
               nullable=False)
        batch_op.drop_column('id')

    # ### end Alembic commands ###
